### ISSUE TITLE
AddBsonClassMap<TMapDocument>() without Parameter

### ISSUE THREAD

**Issue by gmiserez** [SwissLife-OSS/mongo-extensions#16]
Hi, 

With the Mongo API it is possible to call BsonClassMap.RegisterClassMap with and without an action. 
In this extension package however there is only this method: 
>     public IMongoCollectionBuilder<TDocument> AddBsonClassMap<TMapDocument>(
>       Action<BsonClassMap<TMapDocument>> bsonClassMapAction) where TMapDocument : class

For a specific issue that we are currently encountering we need to register a class without any action. 

Would you consider including a method AddBsonClassMap with the following declaration: 
>     public IMongoCollectionBuilder<TDocument> AddBsonClassMap() where TMapDocument : class

**Comment by nscheibe** [comment]
Closed in #18
